Namespace BL
    Public Class Journal

#Region "Main"

        Public Shared Function ListData(ByVal intCompanyID As Integer, ByVal intProgramID As Integer, _
                                        ByVal dtmDateFrom As DateTime, ByVal dtmDateTo As DateTime, ByVal intIDStatus As Integer) As DataTable
            dtmDateTo = dtmDateTo.AddHours(23).AddMinutes(59).AddSeconds(59)
            BL.Server.ServerDefault()
            Return DL.Journal.ListData(intCompanyID, intProgramID, dtmDateFrom, dtmDateTo, intIDStatus)
        End Function

        Public Shared Function ListDataSyncJournal(ByVal intCompanyID As Integer, ByVal intProgramID As Integer, _
                                                   ByVal dtmDateFrom As DateTime, ByVal dtmDateTo As DateTime) As DataTable
            dtmDateTo = dtmDateTo.AddHours(23).AddMinutes(59).AddSeconds(59)
            BL.Server.ServerDefault()
            Return DL.Journal.ListDataSyncJournal(intCompanyID, intProgramID, dtmDateFrom, dtmDateTo)
        End Function

        Private Shared Function GetNewID(ByVal intCompanyID As Integer, ByVal bolIsAutoGenerated As Boolean, ByVal intProgramID As Integer, ByVal dtmDate As DateTime)
            Dim clsCompany As VO.Company = DL.Company.GetDetail(intCompanyID)
            Dim strReturn As String = IIf(bolIsAutoGenerated, "JA", "JT") & Format(dtmDate, "yyMMdd") & "-" & clsCompany.CompanyInitial & "-" & Format(intProgramID, "00") & "-"
            strReturn = strReturn & Format(DL.Journal.GetMaxID(strReturn), "000")
            Return strReturn
        End Function

        Private Shared Function GetNewJournalNo(ByVal intCompanyID As Integer, ByVal dtmDate As DateTime)
            Dim clsCompany As VO.Company = DL.Company.GetDetail(intCompanyID)
            Dim strReturn As String = "JU" & "-" & clsCompany.CompanyInitial & "-" & Format(dtmDate, "yyMMdd")
            strReturn = strReturn & Format(DL.Journal.GetMaxJournalNo(strReturn), "000")
            Return strReturn
        End Function

        Public Shared Function SaveDataDefault(ByVal bolNew As Boolean, ByVal clsData As VO.Journal, ByVal clsDataDetail() As VO.JournalDet) As String
            BL.Server.ServerDefault()
            Try
                DL.SQL.OpenConnection()
                DL.SQL.BeginTransaction()

                clsData.ID = SaveData(bolNew, clsData, clsDataDetail, True)

                DL.SQL.CommitTransaction()
            Catch ex As Exception
                DL.SQL.RollBackTransaction()
                Throw ex
            Finally
                DL.SQL.CloseConnection()
            End Try
            Return clsData.ID
        End Function

        Public Shared Function SaveData(ByVal bolNew As Boolean, ByVal clsData As VO.Journal, ByVal clsDataDetail() As VO.JournalDet, ByVal bolGenerateBukuBesar As Boolean) As String
            If bolNew Or clsData.ID.Trim = "" Then
                bolNew = True
                clsData.ID = GetNewID(clsData.CompanyID, clsData.IsAutoGenerate, clsData.ProgramID, clsData.JournalDate)
                If clsData.JournalNo Is Nothing Then clsData.JournalNo = GetNewJournalNo(clsData.CompanyID, clsData.JournalDate)
                If clsData.JournalNo.Trim = "" Then clsData.JournalNo = GetNewJournalNo(clsData.CompanyID, clsData.JournalDate)
                If DL.Journal.DataExists(clsData.ID) Then
                    Err.Raise(515, "", "ID sudah ada sebelumnya")
                ElseIf Format(clsData.JournalDate, "yyyyMMdd") <= DL.PostGL.LastPostedDate(clsData.CompanyID, clsData.ProgramID) Then
                    Err.Raise(515, "", "Data tidak dapat disimpan. Dikarenakan tanggal transaksi lebih kecil atau sama dengan tanggal Posting Transaksi")
                ElseIf DL.Journal.DataExistsJournalNo(clsData.JournalNo) Then
                    Err.Raise(515, "", "Nomor " & clsData.JournalNo & " sudah terpakai")
                End If
            Else
                '# Get detail for assign JournalNo from Others transaction (Generate Journal)
                Dim clsJournal As New VO.Journal
                If clsData.JournalNo Is Nothing Then
                    clsJournal = DL.Journal.GetDetail(clsData.ID)
                    clsData.JournalNo = clsJournal.JournalNo
                End If

                If DL.Journal.IsDeleted(clsData.ID) Then
                    Err.Raise(515, "", "Data tidak dapat diedit. Dikarenakan data telah dihapus")
                ElseIf DL.Journal.IsPostedGL(clsData.ID) Then
                    Err.Raise(515, "", "Data tidak dapat diedit. Dikarenakan data telah diproses posting data transaksi")
                ElseIf DL.Journal.DataExistsJournalNo(clsData.JournalNo, clsData.ID) Then
                    Err.Raise(515, "", "Nomor " & clsData.JournalNo & " sudah terpakai")
                End If

                If bolGenerateBukuBesar Then
                    '# Get Detail For Delete Buku Besar
                    Dim dtDetail As DataTable = DL.Journal.ListDataDetail(clsData.ID)
                    For Each dr As DataRow In dtDetail.Rows
                        DL.BukuBesar.DeleteData(clsData.ProgramID, clsData.CompanyID, dr.Item("ID"))
                    Next
                End If

                '# Delete Journal Detail
                DL.Journal.DeleteDataDetail(clsData.ID)
            End If

            DL.Journal.SaveData(bolNew, clsData)

            '# Save Data Detail
            For Each clsDetail As VO.JournalDet In clsDataDetail
                If clsDetail Is Nothing Then Exit For
                clsDetail.ID = clsData.ID & "-" & Format(DL.Journal.GetMaxIDDetail(clsData.ID), "000")
                clsDetail.JournalID = clsData.ID
                DL.Journal.SaveDataDetail(clsDetail)
            Next

            '# Save Data Status
            SaveDataStatus(clsData.ID, IIf(bolNew, "BARU", "EDIT"), clsData.LogBy, clsData.Remarks)

            '# Buku Besar
            If bolGenerateBukuBesar Then BL.Journal.GenerateJournal(clsData)

            Return clsData.ID
        End Function

        Public Shared Function GetDetail(ByVal strID As String) As VO.Journal
            BL.Server.ServerDefault()
            Return DL.Journal.GetDetail(strID)
        End Function

        Public Shared Sub DeleteDataDefault(ByVal clsData As VO.Journal)
            BL.Server.ServerDefault()
            Try
                DL.SQL.OpenConnection()
                DL.SQL.BeginTransaction()

                DeleteData(clsData)

                DL.SQL.CommitTransaction()
            Catch ex As Exception
                DL.SQL.RollBackTransaction()
                Throw ex
            Finally
                DL.SQL.CloseConnection()
            End Try
        End Sub

        Public Shared Sub DeleteData(ByVal clsData As VO.Journal)
            If DL.Journal.IsDeleted(clsData.ID) Then
                Err.Raise(515, "", "Data tidak dapat dihapus. Dikarenakan data telah dihapus sebelumnya")
            ElseIf DL.Journal.IsPostedGL(clsData.ID) Then
                Err.Raise(515, "", "Data tidak dapat dihapus. Dikarenakan data telah diproses posting data transaksi")
            Else
                '# Get All Detail for Delete Buku Besar
                Dim dtDetail As DataTable = DL.Journal.ListDataDetail(clsData.ID)
                For Each dr As DataRow In dtDetail.Rows
                    '# Delete Buku Besar
                    DL.BukuBesar.DeleteData(clsData.ProgramID, clsData.CompanyID, dr.Item("ID"))
                Next

                '# Delete Journal
                DL.Journal.DeleteData(clsData.ID)

                '# Save Data Status
                SaveDataStatus(clsData.ID, "DIHAPUS", clsData.LogBy, clsData.Remarks)
            End If
        End Sub

        Public Shared Function PrintFakturBiaya(ByVal strID As String) As DataTable
            BL.Server.ServerDefault()
            Dim dtData As DataTable = DL.Journal.PrintFakturBiaya(strID)
            For Each dr As DataRow In dtData.Rows
                dr.BeginEdit()
                dr.Item("TextOfTotalAmount") = SharedLib.StringUtility.ConvertNumIndo(dr.Item("TotalAmount"))
                dr.EndEdit()
            Next
            dtData.AcceptChanges()
            Return dtData
        End Function

        Public Shared Sub GenerateJournal(ByVal clsData As VO.Journal)
            Dim clsBukuBesar As New VO.BukuBesar

            '# Journal
            Dim dtData As DataTable = DL.Journal.ListDataGenerateJournal(clsData.CompanyID, clsData.ProgramID, clsData.ID)
            For Each dr As DataRow In dtData.Rows
                Dim dtDetail As DataTable = DL.Journal.ListDataDetail(dr.Item("ID"))
                Dim drDebit() As DataRow = dtDetail.Select("DebitAmount>0")
                Dim drCredit() As DataRow = dtDetail.Select("CreditAmount>0")
                Dim drParent() As DataRow
                Dim drChild() As DataRow
                If drDebit.Length = 1 Then
                    drParent = drDebit
                    drChild = drCredit
                Else
                    drParent = drCredit
                    drChild = drDebit
                End If

                '# Save Buku Besar
                For Each dr1 As DataRow In drParent
                    For Each dr2 As DataRow In drChild
                        clsBukuBesar = New VO.BukuBesar
                        clsBukuBesar.CompanyID = clsData.CompanyID
                        clsBukuBesar.ProgramID = clsData.ProgramID
                        clsBukuBesar.ID = ""
                        clsBukuBesar.ReferencesID = dr1.Item("ID")
                        clsBukuBesar.TransactionDate = dr.Item("JournalDate")
                        clsBukuBesar.COAIDParent = dr1.Item("CoAID")
                        clsBukuBesar.COAIDChild = dr2.Item("CoAID")
                        clsBukuBesar.DebitAmount = dr2.Item("CreditAmount")
                        clsBukuBesar.CreditAmount = 0
                        clsBukuBesar.Remarks = dr2.Item("CoAName")
                        clsBukuBesar.LogBy = UI.usUserApp.UserID
                        BL.BukuBesar.SaveData(clsBukuBesar)

                        clsBukuBesar = New VO.BukuBesar
                        clsBukuBesar.CompanyID = clsData.CompanyID
                        clsBukuBesar.ProgramID = clsData.ProgramID
                        clsBukuBesar.ID = ""
                        clsBukuBesar.ReferencesID = dr2.Item("ID")
                        clsBukuBesar.TransactionDate = dr.Item("JournalDate")
                        clsBukuBesar.COAIDParent = dr2.Item("CoAID")
                        clsBukuBesar.COAIDChild = dr1.Item("CoAID")
                        clsBukuBesar.DebitAmount = 0
                        clsBukuBesar.CreditAmount = dr2.Item("CreditAmount")
                        clsBukuBesar.Remarks = dr1.Item("CoAName")
                        clsBukuBesar.LogBy = UI.usUserApp.UserID
                        BL.BukuBesar.SaveData(clsBukuBesar)
                    Next
                Next

                '# Save Buku Besar
                'If drDebit.Count = 1 Then
                '    For Each drD As DataRow In drDebit
                '        clsBukuBesar = New VO.BukuBesar
                '        clsBukuBesar.CompanyID = clsData.CompanyID
                '        clsBukuBesar.ProgramID = clsData.ProgramID
                '        clsBukuBesar.ID = ""
                '        clsBukuBesar.ReferencesID = drD.Item("ID")
                '        clsBukuBesar.TransactionDate = dr.Item("JournalDate")
                '        clsBukuBesar.COAIDParent = drD.Item("CoAID")
                '        clsBukuBesar.COAIDChild = drDebit(0).Item("CoAID")
                '        clsBukuBesar.DebitAmount = drD.Item("DebitAmount")
                '        clsBukuBesar.CreditAmount = 0
                '        clsBukuBesar.Remarks = drD.Item("CoAName")
                '        clsBukuBesar.LogBy = UI.usUserApp.UserID
                '        BL.BukuBesar.SaveData(clsBukuBesar)

                '        clsBukuBesar = New VO.BukuBesar
                '        clsBukuBesar.CompanyID = clsData.CompanyID
                '        clsBukuBesar.ProgramID = clsData.ProgramID
                '        clsBukuBesar.ID = ""
                '        clsBukuBesar.ReferencesID = drD.Item("ID")
                '        clsBukuBesar.TransactionDate = dr.Item("JournalDate")
                '        clsBukuBesar.COAIDParent = drD.Item("CoAID")
                '        clsBukuBesar.COAIDChild = drDebit(0).Item("CoAID")
                '        clsBukuBesar.DebitAmount = 0
                '        clsBukuBesar.CreditAmount = drD.Item("CreditAmount")
                '        clsBukuBesar.Remarks = drD.Item("CoAName")
                '        clsBukuBesar.LogBy = UI.usUserApp.UserID
                '        BL.BukuBesar.SaveData(clsBukuBesar)
                '    Next
                'ElseIf drCredit.Count = 1 Then
                '    For Each drC As DataRow In drCredit
                '        clsBukuBesar = New VO.BukuBesar
                '        clsBukuBesar.CompanyID = clsData.CompanyID
                '        clsBukuBesar.ProgramID = clsData.ProgramID
                '        clsBukuBesar.ID = ""
                '        clsBukuBesar.ReferencesID = drC.Item("ID")
                '        clsBukuBesar.TransactionDate = dr.Item("JournalDate")
                '        clsBukuBesar.COAIDParent = drCredit(0).Item("CoAID")
                '        clsBukuBesar.COAIDChild = drC.Item("CoAID")
                '        clsBukuBesar.DebitAmount = 0
                '        clsBukuBesar.CreditAmount = drC.Item("DebitAmount")
                '        clsBukuBesar.Remarks = drC.Item("Remarks")
                '        clsBukuBesar.LogBy = UI.usUserApp.UserID
                '        BL.BukuBesar.SaveData(clsBukuBesar)

                '        clsBukuBesar = New VO.BukuBesar
                '        clsBukuBesar.CompanyID = clsData.CompanyID
                '        clsBukuBesar.ProgramID = clsData.ProgramID
                '        clsBukuBesar.ID = ""
                '        clsBukuBesar.ReferencesID = drC.Item("ID")
                '        clsBukuBesar.TransactionDate = dr.Item("JournalDate")
                '        clsBukuBesar.COAIDParent = drC.Item("CoAID")
                '        clsBukuBesar.COAIDChild = drCredit(0).Item("CoAID")
                '        clsBukuBesar.DebitAmount = drC.Item("DebitAmount")
                '        clsBukuBesar.CreditAmount = 0
                '        clsBukuBesar.Remarks = drC.Item("Remarks")
                '        clsBukuBesar.LogBy = UI.usUserApp.UserID
                '        BL.BukuBesar.SaveData(clsBukuBesar)
                '    Next
                'End If
            Next
        End Sub

        Public Shared Sub DeleteJournal(ByVal intProgramID As Integer, ByVal intCompanyID As Integer, strID As String)
            '# Delete Buku Besar Sales
            DL.BukuBesar.DeleteData(intProgramID, intCompanyID, strID)

            '# Delete Journal
            DL.Journal.DeleteData(strID)
        End Sub

        Public Shared Sub PostData(ByVal intCompanyID As Integer, ByVal intProgramID As Integer, _
                                   ByVal dtmDateFrom As DateTime, ByVal dtmDateTo As DateTime)
            'Dim clsBukuBesar As New VO.BukuBesar
            'Dim dtData As DataTable = DL.Journal.ListDataOutstandingPostGL(intCompanyID, intProgramID, dtmDateFrom, dtmDateTo)
            'DL.Journal.PostGL(intCompanyID, intProgramID, dtmDateFrom, dtmDateTo, UI.usUserApp.UserID)
            'For Each dr As DataRow In dtData.Rows

            '    '# Save Data Status
            '    SaveDataStatus(dr.Item("ID"), "POSTING DATA TRANSAKSI", UI.usUserApp.UserID, "")

            '    Dim dtDetail As DataTable = DL.Journal.ListDataDetail(dr.Item("ID"))
            '    Dim drDebit() As DataRow = dtDetail.Select("DebitAmount>0")
            '    Dim drCredit() As DataRow = dtDetail.Select("CreditAmount>0")

            '    '# Save Buku Besar
            '    If drDebit.Count = 1 Then
            '        For Each drC As DataRow In drCredit
            '            clsBukuBesar = New VO.BukuBesar
            '            clsBukuBesar.CompanyID = intCompanyID
            '            clsBukuBesar.ProgramID = intProgramID
            '            clsBukuBesar.ID = ""
            '            clsBukuBesar.ReferencesID = drC.Item("ID")
            '            clsBukuBesar.TransactionDate = dr.Item("JournalDate")
            '            clsBukuBesar.COAIDParent = drDebit(0).Item("CoAID")
            '            clsBukuBesar.COAIDChild = drC.Item("CoAID")
            '            clsBukuBesar.DebitAmount = drC.Item("CreditAmount")
            '            clsBukuBesar.CreditAmount = 0
            '            clsBukuBesar.Remarks = drC.Item("Remarks")
            '            clsBukuBesar.LogBy = UI.usUserApp.UserID
            '            BL.BukuBesar.SaveData(clsBukuBesar)

            '            clsBukuBesar = New VO.BukuBesar
            '            clsBukuBesar.CompanyID = intCompanyID
            '            clsBukuBesar.ProgramID = intProgramID
            '            clsBukuBesar.ID = ""
            '            clsBukuBesar.ReferencesID = drC.Item("ID")
            '            clsBukuBesar.TransactionDate = dr.Item("JournalDate")
            '            clsBukuBesar.COAIDParent = drC.Item("CoAID")
            '            clsBukuBesar.COAIDChild = drDebit(0).Item("CoAID")
            '            clsBukuBesar.DebitAmount = 0
            '            clsBukuBesar.CreditAmount = drC.Item("CreditAmount")
            '            clsBukuBesar.Remarks = drC.Item("Remarks")
            '            clsBukuBesar.LogBy = UI.usUserApp.UserID
            '            BL.BukuBesar.SaveData(clsBukuBesar)
            '        Next
            '    ElseIf drCredit.Count = 1 Then
            '        For Each drD As DataRow In drDebit
            '            clsBukuBesar = New VO.BukuBesar
            '            clsBukuBesar.CompanyID = intCompanyID
            '            clsBukuBesar.ProgramID = intProgramID
            '            clsBukuBesar.ID = ""
            '            clsBukuBesar.ReferencesID = drD.Item("ID")
            '            clsBukuBesar.TransactionDate = dr.Item("JournalDate")
            '            clsBukuBesar.COAIDParent = drCredit(0).Item("CoAID")
            '            clsBukuBesar.COAIDChild = drD.Item("CoAID")
            '            clsBukuBesar.DebitAmount = 0
            '            clsBukuBesar.CreditAmount = drD.Item("DebitAmount")
            '            clsBukuBesar.Remarks = drD.Item("Remarks")
            '            clsBukuBesar.LogBy = UI.usUserApp.UserID
            '            BL.BukuBesar.SaveData(clsBukuBesar)

            '            clsBukuBesar = New VO.BukuBesar
            '            clsBukuBesar.CompanyID = intCompanyID
            '            clsBukuBesar.ProgramID = intProgramID
            '            clsBukuBesar.ID = ""
            '            clsBukuBesar.ReferencesID = drD.Item("ID")
            '            clsBukuBesar.TransactionDate = dr.Item("JournalDate")
            '            clsBukuBesar.COAIDParent = drD.Item("CoAID")
            '            clsBukuBesar.COAIDChild = drCredit(0).Item("CoAID")
            '            clsBukuBesar.DebitAmount = drD.Item("DebitAmount")
            '            clsBukuBesar.CreditAmount = 0
            '            clsBukuBesar.Remarks = drD.Item("Remarks")
            '            clsBukuBesar.LogBy = UI.usUserApp.UserID
            '            BL.BukuBesar.SaveData(clsBukuBesar)
            '        Next
            '    End If
            'Next
        End Sub

        Public Shared Sub UnpostData(ByVal intCompanyID As Integer, ByVal intProgramID As Integer, _
                                     ByVal dtmDateFrom As DateTime, ByVal dtmDateTo As DateTime)
            Dim dtData As DataTable = DL.Journal.ListDataOutstandingPostGL(intCompanyID, intProgramID, dtmDateFrom, dtmDateTo)
            DL.Journal.UnpostGL(intCompanyID, intProgramID, dtmDateFrom, dtmDateTo)
            For Each dr As DataRow In dtData.Rows
                '# Save Data Status
                SaveDataStatus(dr.Item("ID"), "CANCEL POSTING DATA TRANSAKSI", UI.usUserApp.UserID, "")
            Next

        End Sub

#End Region

#Region "Detail"

        Public Shared Function ListDataDetail(ByVal strJournalID As String) As DataTable
            BL.Server.ServerDefault()
            Return DL.Journal.ListDataDetail(strJournalID)
        End Function

#End Region

#Region "Status"

        Public Shared Function ListDataStatus(ByVal strJournalID As String) As DataTable
            BL.Server.ServerDefault()
            Return DL.Journal.ListDataStatus(strJournalID)
        End Function

        Private Shared Sub SaveDataStatus(ByVal strJournalID As String, ByVal strStatus As String, ByVal strStatusBy As String, _
                                         ByVal strRemarks As String)
            Dim clsData As New VO.JournalStatus
            clsData.ID = strJournalID & "-" & Format(DL.Journal.GetMaxIDStatus(strJournalID), "000")
            clsData.JournalID = strJournalID
            clsData.Status = strStatus
            clsData.StatusBy = strStatusBy
            clsData.StatusDate = Now
            clsData.Remarks = strRemarks
            DL.Journal.SaveDataStatus(clsData)
        End Sub

#End Region

    End Class

End Namespace

